-- Generated by backend/ingestion/generate_assessment_directory_seed.mjs
-- Idempotent seed data for the public assessment directory tables.

BEGIN;

INSERT INTO assessment_modules (module_cn, module_code, active, sort_order)
VALUES
  ('能力与发展', 2, true, 1),
  ('身心健康', 1, true, 2),
  ('家长参与', 3, true, 3)
ON CONFLICT (module_cn) DO UPDATE SET
  module_code = EXCLUDED.module_code,
  active = EXCLUDED.active,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

INSERT INTO assessment_groups (code, title_en, title_cn, title_full, module_cn, module_code, active, sort_order)
VALUES
  ('MWI', 'Multiple Wisdom and Intelligence', '多维智慧与智力', 'EQAI多维智慧与智力问卷', '能力与发展', 2, true, 1),
  ('SR', 'School Refusal', '厌学', 'EQAI厌学自评量表', '身心健康', 1, true, 2),
  ('ER_Aware', '(Negative) Emotional Regulation - Emotional Awareness and Understanding', '(负面)情绪管理 - 情绪的觉察与理解', 'EQAI负面情绪管理量表', '能力与发展', 2, true, 3),
  ('ER_Accept', '(Negative) Emotional Regulation - Emotion Acceptance', '(负面)情绪管理 - 情绪接纳', 'EQAI负面情绪管理量表', '能力与发展', 2, true, 4),
  ('ER_ImpulseControl', '(Negative) Emotional Regulation - Impulse Control', '(负面)情绪管理 - 冲动控制', 'EQAI负面情绪管理量表', '能力与发展', 2, true, 5),
  ('ER_Strategy', '(Negative) Emotional Regulation - Flexibility of Strategies', '(负面)情绪管理 - 策略运用', 'EQAI负面情绪管理量表', '能力与发展', 2, true, 6),
  ('PS_Authoritative', 'Parenting Styles - Authoritative', '家长养育模式 - 权威型', 'EQAI家长养育模式问卷', '家长参与', 3, true, 7),
  ('PS_Authoritarian', 'Parenting Styles - Authoritarian', '家长养育模式 - 专制型', 'EQAI家长养育模式问卷', '家长参与', 3, true, 8),
  ('PS_Permissive', 'Parenting Styles - Permissive', '家长养育模式 - 宽容型', 'EQAI家长养育模式问卷', '家长参与', 3, true, 9),
  ('Soc_Stress', 'Social Stress', '人际关系压力', 'EQAI人际关系压力量表', '身心健康', 1, true, 10),
  ('SSD', 'Somatic Symptom Disorder', '躯体性问题', 'EQAI躯体化症状量表', '身心健康', 1, true, 11),
  ('Aca_Competence', 'Academic Competence', '学业能力', 'EQAI学业能力量表', '能力与发展', 2, true, 12),
  ('ADHD_Inattention', 'Attention-Deficit/Hyperactivity Disorder - Inattention', '注意力缺陷多动障碍 - 注意缺陷', 'EQAI注意力缺陷多动障碍筛查量表', '身心健康', 1, true, 13),
  ('ADHD_Hyperact', 'Attention-Deficit/Hyperactivity Disorder - Hyperactivity/Impulsivity', '注意力缺陷多动障碍 - 冲动/多动', 'EQAI注意力缺陷多动障碍筛查量表', '身心健康', 1, true, 14),
  ('ADHD _Oppose', 'Attention-Deficit/Hyperactivity Disorder - Opposition/Conflict', '注意力缺陷多动障碍 - 违抗/冲突', 'EQAI注意力缺陷多动障碍筛查量表', '身心健康', 1, true, 15),
  ('ADHD_EmoReg', 'Attention-Deficit/Hyperactivity Disorder - EmoRegulation', '注意力缺陷多动障碍 - 情绪调节困难', 'EQAI注意力缺陷多动障碍筛查量表', '身心健康', 1, true, 16),
  ('ADHD_Motiv', 'Attention-Deficit/Hyperactivity Disorder - Delay Aversion', '注意力缺陷多动障碍 - 动机/延迟满足', 'EQAI注意力缺陷多动障碍筛查量表', '身心健康', 1, true, 17),
  ('16PF', 'Cattell''s 16 Personality Factors Test', '卡特尔十六种人格因素测验', 'EQAI人格因素测验', '能力与发展', 2, true, 18),
  ('Achenbach_YSR', 'Achenbach System - Youth Self-Report', '青少年自评量表', 'EQAI身心健康自评筛查', '身心健康', 1, true, 19),
  ('Achenbach_CBCL', 'Achenbach System - Child Behavior Checklist', '儿童青少年行为量表', 'EQAI身心健康他评筛查（家长）', '家长参与', 3, true, 20)
ON CONFLICT (code) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_cn = EXCLUDED.title_cn,
  title_full = EXCLUDED.title_full,
  module_cn = EXCLUDED.module_cn,
  module_code = EXCLUDED.module_code,
  active = EXCLUDED.active,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

INSERT INTO assessment_measures (group_code, code, name, desc_casual, desc_academic, active, sort_order)
VALUES
  ('MWI', '01', '情绪理解与社交', '这套题在看你能不能察觉别人的情绪，是否容易理解他人感受，遇到矛盾时能否平和沟通，以及在相处中是否能让关系更融洽、彼此都感到被理解。', '反映个体在情绪觉察、理解与调节方面的特点，以及在人际交往中维系良好关系的倾向。它关注对他人情绪的感知能力、共情反应、应对冲突的方式及适应性社交行为的表现。', true, 1),
  ('MWI', '02', '自我愉悦与情绪调节', '这个部分看你遇到不顺心的事情时，能不能调整自己的情绪，以及会不会用适合自己的方法让自己冷静或好受一些。也了解你面对批评或变化时的情绪反应。', '反映个体在面对压力或负面情绪时的情绪调节能力，体现为对自身情绪的觉察、接纳与恢复水平。高分者通常能较好地应对挫折，保持内心平稳，展现出较强的心理适应性。', true, 2),
  ('MWI', '03', '幽默与趣味感知', '这套题想了解你在生活中能不能发现好笑的瞬间，会不会用幽默让气氛变轻松。比如遇到尴尬或压力时，你是否能自然地说句话，让大家都笑出来。', '反映个体在日常生活中感知和运用幽默的倾向，体现其以轻松态度应对情境、调节情绪反应及促进人际互动的特征。高分者通常更善于捕捉趣味元素，并在社交中自然流露幽默感。', true, 3),
  ('MWI', '04', '身心健康与生活平衡', '这套题想了解你在忙碌中是否能照顾好自己，比如有没有好好休息、按时吃饭、坚持锻炼和放松。也看看你能不能察觉到身体累或心情变差，并主动做出调整。', '反映个体在日常生活与工作中调节精力、维持身心平衡的倾向，表现为对休息、饮食、锻炼等自我照护行为的持续关注，以及对疲劳和压力信号的敏感性与应对能力，强调节奏感和自我调适的稳定性。', true, 4),
  ('MWI', '05', '陪伴与共情', '这些题目在看你平时能不能注意到别人的情绪变化，是否愿意在朋友开心或低落时陪伴他们，能否真正理解他们的感受，并自然地给予回应。', '反映个体在人际交往中感知他人情绪、给予情感回应及维持共情联结的稳定倾向，体现其情绪觉察力、关怀表达以及在关系中持续提供理解支持的特点。', true, 5),
  ('MWI', '06', '乐观与积极心态', '这些题目用来了解你在遇到挫折时，能否保持信心，看到希望，调节情绪，并用自己的正能量带动身边人一起面对困难。', '反映个体在压力或逆境中维持积极心态的倾向，体现其对未来的乐观预期、情绪调节能力，以及在困境中寻找意义并支持他人心理适应的特质。', true, 6),
  ('MWI', '07', '逆境应对力与心理韧性', '这个部分想了解你面对困难或压力时，能否保持冷静、不轻易放弃，并努力寻找解决办法。它关注你如何调整心态，坚持目标，并在挑战中不断进步。', '反映个体在压力、挫折或环境变化中的心理调适能力，体现情绪稳定、目标坚持及从逆境中成长的倾向。高分者通常具备良好的自我调节能力，能积极应对挑战并持续采取行动。', true, 7),
  ('MWI', '08', '慧商', '这些题目用来了解一个人是否能从生活中获得领悟，遇事时善于冷静思考，理解问题的本质，并做出成熟应对。', '反映个体对人生经验的深层理解与整合能力，体现其在面对复杂问题时的觉察水平、反思习惯及对长远意义的关注倾向。', true, 8),
  ('MWI', '09', '逻辑思维与解决问题', '这些题目关注你平时遇到难题时，能否理清思路、找出解决方法，是否愿意深入思考事情背后的原因，并从经历中总结经验。', '反映个体在面对复杂信息时，运用逻辑分析、整合线索并提炼核心规律的认知特征，体现其系统思考与从经验中构建理解的能力倾向。', true, 9),
  ('MWI', '10', '勇气与决断', '这套题想了解你在遇到困难或突发状况时，能不能稳住自己、敢不敢做决定，以及会不会因害怕犯错而犹豫不前。它关注你在压力下是否还能坚持行动，勇敢面对该承担的事。', '反映个体在压力与不确定性中保持镇定、自主决策并采取行动的心理倾向，体现面对挑战时的决断力、行动意愿及对挫折的包容态度。具有此特质者通常信赖自身判断，能在信息有限时做出选择，并在受挫后继续前行。', true, 10),
  ('MWI', '11', '目标感与持续行动力', '这组题目用来了解你是否能清楚设定目标，合理安排步骤，并坚持完成。它关注你在遇到困难时能否调整自己，不轻易放弃，一步步向前推进并把事情做完。', '反映个体在追求目标过程中表现出的持续行动力，包括明确目标设定、合理规划步骤、自我调节进度以及在挑战中保持方向的能力，体现为有意识的坚持与时间管理的稳定性。', true, 11),
  ('MWI', '12', '团队协作与信任', '这个部分用来了解你在团队中是否愿意和他人合作，能不能有效沟通，遇到意见不合时能否冷静应对，以及是否信任队友并共同努力达成目标的真实想法和日常表现。', '衡量个体在团队中建立互信、促进沟通与协作的心理特质，表现为对成员能力的信赖、面对冲突时的理性态度、调和分歧的主动性，以及协调个人与集体目标的能力，反映其推动团队合作的内在倾向。', true, 12),
  ('MWI', '13', '执行与组织能力', '这套题在了解一个人做事是否条理清晰，能否合理安排时间和步骤，遇到困难时是否能灵活应对，让事情有条不紊地进行。', '反映个体在实现目标过程中组织计划、分配资源及调整行动的心理特征，体现其在复杂情境中保持效率与持续推进任务的能力。', true, 13),
  ('MWI', '14', '判断与责任意识', '这些题目用来了解一个人平时做决定时，会不会仔细核实信息，能否独立判断对错，以及是否敢于承认失误并从中学习。', '衡量个体在信息处理过程中注重证据、识别逻辑漏洞的能力，以及在决策时保持客观、审慎并承担相应后果的心理特质，反映其理性思维与责任意识的结合。', true, 14),
  ('MWI', '15', '言语策略与表达艺术', '这套题了解你说话时会不会用生动的方式表达，比如打比方、讲笑话或调整语气，让别人更容易理解也更愿意听你说话。它关注你如何让语言更有趣、更有感染力。', '反映个体在口头交流中运用语言策略增强表达效果的心理特点，体现其在修辞手法、表达方式调节和信息呈现生动性方面的倾向。高分者更倾向于使用比喻、幽默或类比等技巧提升沟通的吸引力与感染力。', true, 15),
  ('MWI', '16', '网络沟通与传播判断力', '这套题了解你上网时能否分辨信息真假，说话是否考虑他人感受，能否清楚表达自己，并负责任地分享内容。', '反映个体在网络环境中理解、表达与评估信息的综合倾向，体现对信息真实性、传播影响及沟通方式的综合判断，表征其在网络交流中的理性思考与责任意识。', true, 16),
  ('MWI', '17', '书面表达与思维能力', '这套题了解你在写作文或表达想法时，能否理清思路，有条理地写出观点，让人看得明白，以及是否会用恰当的例子和逻辑来支持自己的看法。', '反映个体在书面表达中组织思维、构建逻辑结构及清晰传递信息的心理倾向，体现其在写作过程中对条理性、论证严谨性和表达清晰度的关注程度。', true, 17),
  ('MWI', '18', '文学鉴赏与感受力', '这个问题想了解你在读小说、诗歌或散文时，是否容易被文字感染，喜欢体会其中的情感和深层含义，以及阅读给你带来的感受和思考有多深刻。', '衡量个体在接触文学作品时，对语言表达、情感内涵、象征意义及作者意图的觉察与兴趣，体现其通过阅读获取审美体验、情感共鸣和思想启迪的倾向性。', true, 18),
  ('MWI', '19', '审美与视觉感知', '这些问题想了解你对颜色搭配、画面结构和整体美感的敏感程度，比如是否容易察觉艺术作品或周围环境中的视觉细节，以及是否常被美的事物吸引。', '衡量个体对视觉元素如色彩、构图与空间关系的感知敏锐度，以及对艺术形式和美学特征的理解与评价倾向，反映其在审美情境中的认知与情感反应模式。', true, 19),
  ('MWI', '20', '生活品味与艺术感知', '这个部分想了解你是否喜欢在生活中寻找美和表达美，比如欣赏音乐、设计空间或留意物品的搭配，看你是否习惯让日常环境更顺眼、更舒心。', '反映个体对美感体验的偏好与追求，表现为对艺术形式、环境氛围及生活细节的敏锐感知和主动塑造，体现通过审美选择提升日常生活质量的内在倾向。', true, 20),
  ('MWI', '21', '仪态表演与形象管理', '这套问题在了解你在不同场合是否会留意自己的穿着、言行和留给别人的印象，以及能否根据环境调整自己，表现得更恰当自然。', '反映个体在社会情境中通过仪表、举止和形象管理来展现适宜行为的倾向，体现其对自我表达的重视程度，以及依据环境调节外在表现的能力特征。', true, 21),
  ('SR', '01', '学业成就情绪负担', NULL, NULL, true, 1001),
  ('SR', '02', '学习动机丧失', NULL, NULL, true, 1002),
  ('SR', '03', '学习策略低效与认知超负荷', NULL, NULL, true, 1003),
  ('SR', '04', '校园人际关系与归属感', NULL, NULL, true, 1004),
  ('SR', '05', '家庭压力与支持缺乏', NULL, NULL, true, 1005),
  ('SR', '06', '自我认同与未来焦虑', NULL, NULL, true, 1006),
  ('ER_Aware', '01', '情绪意识/感知力缺乏', NULL, '情绪意识，又称情绪感知力，即对自身情绪状态的觉察。缺乏情绪意识的人可能无法将情绪的生理信号（胃不舒服，身体虚弱，胸闷等）归因为情绪的产生，也不会关注自己是否出现某一种负面情绪。举例来说，当一个学生因第二天要公开演讲而感到焦虑时，他的胃部持续发紧，手心出汗。如果他缺乏情绪意识，他可能只会把这些生理信号简单归因为“胃不舒服”或“身体有点虚”，并开始担心自己是否生病了。他无法将身体的紧张感识别为“焦虑”或“紧张”这种情绪正在产生的信号，因此也无法针对情绪本身进行任何调节，只能陷于对身体不适的困惑与担忧之中。无法觉察到自己具体的情绪会让孩子无法正确表达自己的情绪和需要，而难以使用情绪调节策略。', true, 2001),
  ('ER_Aware', '02', '情绪清晰度缺乏', NULL, '情绪清晰度，指的是个体理解、区分和精确标注与表达自身具体情绪体验的能力。如果说“情绪意识”是觉察到情绪信号的存在，那么“情绪清晰度”则是能够解读这些信号的具体含义。它回答的是“我感受到的究竟是什么”这一问题，涉及对情绪状态的归因、复杂情绪的辨析（如区分失望、悲伤与愤怒）以及情绪混合体的识别（如悲喜交加）。例如，考试失利后，缺乏情绪清晰度的学生会陷入一种模糊的负面混沌感中，只能用“很烦”“难受”等笼统词汇描述内心。他们无法辨析其中究竟混杂着失望、羞耻、恐惧还是愤怒，如同面对一团无法理清的情绪乱麻。这种“情绪模糊”会导致调节策略错配（如用打游戏宣泄或逃避），造成沟通障碍（无法向他人有效表达），并可能使未被理解的痛苦逐渐内化为持续的焦虑或低落，从而影响学习与人际适应。', true, 2002),
  ('ER_Accept', '03', '非接纳情绪反应', NULL, '指的是个体不愿接受情绪，不仅在经历负面情绪，更在抗拒和批判自己的情绪体验，将情绪本身视为“错误”、“脆弱”或“不应该的”。这常导致“情绪叠加”：即原始情绪（如悲伤）之上，又叠加了因该情绪而产生的次生情绪（如羞耻与自责），形成恶性循环，成为情绪管理困难的重要表现之一。', true, 3001),
  ('ER_ImpulseControl', '04', '目标导向行为困难', NULL, '指个体在情绪激动时，或在经历负面情绪时，难以集中注意力、组织思维或继续执行既定任务的能力缺陷。其核心在于情绪的干扰作用削弱了认知资源的有效分配与行为持续性。', true, 4001),
  ('ER_ImpulseControl', '05', '冲动控制困难', NULL, '指个体在情绪高涨或痛苦时，难以抑制立即的、通常是适应不良的行为反应的倾向。这些行为旨在快速缓解情绪痛苦，但往往带来负面后果。', true, 4002),
  ('ER_Strategy', '06', '情绪调节策略受限', NULL, '指个体在情绪激动时，主观感到缺乏有效的方法来管理和缓解情绪，陷入“无能为力”或“别无选择”的困境，常伴有对情绪状态持久性的悲观预期，或使用非适应性的情绪调节策略如回避，自我贬低等。', true, 5001),
  ('ER_Strategy', '07', '非适应性情绪调节策略', NULL, '本子维度旨在系统测量儿童及青少年在应对情绪唤起时，所习惯性采用的、长期来看对心理社会功能有害的调节策略。非适应性情绪调节策略是指那些可能暂时缓解情绪痛苦，但会阻碍长期目标达成、损害社会关系或加剧情绪问题的行为与认知模式。非适应性情绪调节策略包括行为回避（avoidance，如面对困难任务时退缩）、认知反刍（rumination，反复思考负面事件及感受）、情绪压抑（suppression，抑制情绪的表达）、冲动发泄（aggressive actions，如言语或身体攻击），以及将数字媒体使用作为逃避现实情绪的手段等。在现实中，此类策略常体现为：青少年在经历学业挫折或社交焦虑后，不是寻求解决方法或支持，而是陷入对自身失败的反复回想（反刍），或长时间沉浸在网络游戏、社交媒体中以逃离负面情绪（行为逃避），这可能导致情绪失调的恶性循环和问题性网络使用的风险增高。', true, 5002),
  ('PS_Authoritative', '01', '情感支持', NULL, '本分维度聚焦父母在孩子出现情绪时的回应方式：包括是否能注意到情绪信号、是否愿意倾听、是否提供安抚与共情、是否允许孩子表达，以及是否在情绪稳定后再进入问题解决。', true, 6001),
  ('PS_Authoritative', '02', '讲道理与引导', NULL, '指父母在管教和引导孩子行为时，是否通过解释原因、讨论后果、帮助分析情境等方式，引导孩子理解规则的意义，而不仅仅依靠命令或惩罚。这一分维度强调父母是否帮助孩子将外在要求转化为内在理解，从而逐步形成自我调节能力。', true, 6002),
  ('PS_Authoritative', '03', '有结构的自主支持', NULL, '指父母在设定清晰规则和边界的前提下，逐步给予孩子与其发展阶段相匹配的选择权和决策空间。该分维度强调，自主并非完全放手，而是在父母持续参与和引导下进行。父母既明确哪些事情不可协商，也在合适范围内允许孩子表达意见、参与决策并尝试自己的方式。', true, 6003),
  ('PS_Authoritarian', '04', '等级化权威信念', NULL, '指父母对亲子关系中权力结构的基本看法，即是否认为父母应处于绝对权威地位，而孩子主要应以服从和听话作为行为准则。在这一信念框架下，父母通常认为规则和决定不需要向孩子解释，孩子提出质疑可能被视为不尊重或挑战权威。', true, 7001),
  ('PS_Authoritarian', '05', '心理控制与界限侵入', NULL, '指父母通过操控孩子的情绪、想法或自我评价来影响其行为，而非通过清晰规则或合理引导进行管教。这类做法通常不表现为直接惩罚，而是通过内疚、羞辱、否定、情感撤回或过度干预隐私等方式，使孩子顺从父母期望。该分维度关注的是父母是否尊重孩子的心理界限与情感独立性，而非父母是否关心孩子。', true, 7002),
  ('PS_Authoritarian', '06', '惩罚性管教', NULL, '指父母在纠正或制止孩子不当行为时，主要依赖惩罚、威慑或强制手段，而较少使用解释、引导或协商的方式。这类管教方式强调通过制造不适或恐惧来迅速改变行为，其形式可以包括言语威胁、剥夺权利、体罚或强制性约束等。该分维度关注的是父母是否将惩罚视为主要或必要的管教工具，而非惩罚的频率或严重程度本身。', true, 7003),
  ('PS_Permissive', '07', '反限制信念', NULL, '指父母对规则、约束和管教介入的基本看法，即是否认为对孩子施加限制会阻碍其自然发展，或认为过多干预并非必要甚至有害。持有此类信念的父母往往强调孩子应“顺其自然”“自己摸索”，并倾向于减少规则和要求的设定。本分维度关注的是父母对限制本身的态度，而非实际行为是否完全放任。', true, 8001),
  ('PS_Permissive', '08', '低结构与低引导', NULL, '指父母在日常养育中较少为孩子提供清晰、稳定的规则、期望和行为指导，也较少主动介入孩子的行为发展过程。该分维度关注的是父母是否在生活安排、行为规范和问题处理上提供持续而一致的方向感，而非父母是否关心孩子或与孩子关系亲近。在这一模式下，父母往往对孩子的行为采取被动或延迟回应，更多在问题变得明显或严重时才介入。', true, 8002),
  ('PS_Permissive', '09', '育儿信心不足', NULL, '指父母在育儿过程中，对自身引导、管教和做决定能力的信心较低，常感到不确定、犹豫或缺乏把握。本分维度关注的是父母对自身育儿角色的自我效能感，而非其是否关心孩子或是否投入时间。在这种情况下，父母可能避免设定规则、回避冲突，或在孩子反对时轻易让步，并非出于明确的养育理念，而是源于对“我这样做是否正确”的不安。', true, 8003),
  ('Soc_Stress', NULL, '师生关系压力', NULL, NULL, true, 9001),
  ('Soc_Stress', NULL, '同学关系压力(e.g., 霸凌)', NULL, NULL, true, 9002),
  ('Soc_Stress', NULL, '网络社交压力', NULL, NULL, true, 9003),
  ('SSD', NULL, '睡眠质量', NULL, NULL, true, 10001),
  ('Aca_Competence', '01', '内在目标定向', NULL, NULL, true, 11001),
  ('Aca_Competence', '02', '任务价值与兴趣', NULL, NULL, true, 11002),
  ('Aca_Competence', '03', '成功期望', NULL, NULL, true, 11003),
  ('Aca_Competence', '04', '掌握效能感', NULL, NULL, true, 11004),
  ('Aca_Competence', '05', '组织策略', NULL, NULL, true, 11005),
  ('Aca_Competence', '06', '学习迁移', NULL, NULL, true, 11006),
  ('Aca_Competence', '07', '精细加工与整合', NULL, NULL, true, 11007),
  ('Aca_Competence', '08', '批判性思维与评估', NULL, NULL, true, 11008),
  ('Aca_Competence', '09', '任务表现监测', NULL, NULL, true, 11009),
  ('Aca_Competence', '10', '认知过程监控', NULL, NULL, true, 11010),
  ('Aca_Competence', '11', '时间与学习环境管理', NULL, NULL, true, 11011),
  ('Aca_Competence', '12', '努力管理', NULL, NULL, true, 11012),
  ('Aca_Competence', '13', '同伴学习', NULL, NULL, true, 11013),
  ('Aca_Competence', '14', '求助策略', NULL, NULL, true, 11014),
  ('ADHD_Inattention', '01', '持续性注意困难', NULL, '持续性注意困难是指个体在较长时间内维持对任务、信息或目标的专注能力不足，表现为注意力易中断、难以长时间投入单一活动，以及在无外部提醒下难以完成持续性认知任务。 持续性注意困难被界定为：个体在无外部强制条件下，难以在一段时间内保持对单一目标、任务或信息的稳定注意状态。该维度不等同于单纯的分心，而强调“时间维度上的注意崩解”，尤其在学习、阅读、听讲与数字环境中表现突出。因此，本亚维度的测量聚焦于注意维持时长、任务中断频率以及主观专注体验。', true, 12001),
  ('ADHD_Inattention', '02', '注意分配问题与易分心', NULL, '注意分配与易分心是指个体在多刺激或多任务环境中，难以有效选择、维持或切换注意焦点的能力缺陷，表现为对无关刺激高度敏感、注意资源被频繁占用，以及难以抑制干扰信息。该亚维度强调注意的选择性与抑制功能，区别于持续性注意，更关注注意控制的质量。注意分配与易分心亚维度聚焦于个体在存在干扰源时对注意焦点的调节能力，涵盖对外界刺激的敏感性、抑制无关信息的能力以及在多任务情境中的注意稳定性。与持续性注意不同，该维度强调“控制失败”而非“耐力不足”，尤其适用于数字化、高刺激环境下的注意评估。因此，其测量条目充分反映现实中常见的干扰源（如通知、声音、视觉信息），并捕捉个体对注意失控的主观体验。 ', true, 12002),
  ('ADHD_Inattention', '03', '注意启动与任务进入困难', NULL, '注意启动与任务进入困难是指个体在开始一项需要注意投入的任务时，难以迅速调动认知资源并进入专注状态，表现为拖延启动、迟迟无法“进入状态”，以及在任务开始阶段产生显著心理阻力。该维度不同于持续性注意与易分心，强调注意的启动阶段而非维持或控制阶段。 注意启动与任务进入困难被界定为个体在面对需要注意投入的任务时，难以迅速激活专注状态并转入有效执行的倾向。该维度强调“开始之前的停滞”，而非任务过程中的分心或疲劳，尤其在学习、自主任务与低外部结构环境中表现显著。结合理论、现有工具与社交媒体表征，该维度具有明确的认知与行为边界，且在现有注意缺陷测量中往往被低估。 ', true, 12003),
  ('ADHD_Hyperact', '04', '行为抑制与冲动控制困难', NULL, '行为抑制与冲动控制困难是指个体在面对即时刺激、情绪或反应冲动时，难以延迟、抑制或调节自身行为的倾向，表现为“想到就做”“来不及思考后果”以及频繁打断、插话或冲动决策。行为抑制与冲动控制困难被界定为个体在需要延迟反应、权衡后果或遵守行为规范时，难以抑制即时行为冲动的稳定倾向。该维度强调“反应之前的失控”，而非活动水平本身，尤其适用于评估青少年在社交互动、情绪情境与数字环境中的冲动表现。因此，条目设计同时覆盖行为层面与主观体验层面，具有较好的生态效度。 ', true, 13001),
  ('ADHD_Hyperact', '05', '心理与言语多动', NULL, '心理与言语多动是指个体在认知与言语层面表现出的过度活跃状态，具体表现为思维跳跃、内心难以安静、想法不断涌现，以及说话过多、语速过快或难以抑制表达冲动。与传统以身体活动为核心的“多动”不同，该亚维度强调内在认知活动与言语输出的过度激活，在青少年与青年群体中尤为常见。心理与言语多动被界定为个体在缺乏外界刺激时，仍持续体验到思维与言语层面的过度活跃状态。该维度强调多动的“内化表现”，区别于身体活动水平，尤其适用于评估青春期及以上群体中不易被传统量表捕捉的多动形式。因此，测量覆盖思维速度、内心躁动、言语输出控制等方面，并避免将其简单等同于外向性或社交性。', true, 13002),
  ('ADHD_Hyperact', '06', '活动水平调节困难', NULL, '活动水平调节困难是指个体在不同情境下难以根据环境要求调节自身活动强度与身体状态，表现为坐立不安、频繁动作、难以保持静止，或在需要安静的场合中活动水平明显偏高。该维度是传统 ADHD 多动表现的核心，但在青少年阶段常以“细微、持续的动作”而非剧烈跑动呈现。活动水平调节困难被界定为个体在需要保持相对静止或低活动状态的情境中，难以有效调节身体活动强度的稳定倾向。该维度强调“活动量与情境要求的不匹配”，而非单纯的精力旺盛。其测量覆盖不同场景下的身体不安、小动作频率及主观控制感，以避免将多动简单等同于活跃或外向。', true, 13003),
  ('ADHD _Oppose', '07', '权威对立与规则抵触', NULL, '权威对立与规则抵触是指个体在面对外部权威（如教师、家长、制度要求）或明确规则时，表现出持续的抗拒、反驳或不配合倾向，常以争辩、顶撞、故意不遵守规则等形式出现。该维度并非单纯的“不听话”，而强调一种稳定的互动模式，即在权力不对等关系中对控制与要求的负向反应。权威对立与规则抵触被界定为个体在面对外部要求、规范或权威指令时，倾向于以反驳、抗拒或消极不配合方式回应的稳定特征。该维度强调互动关系中的“对抗性反应模式”，而非偶发的不顺从行为。测量时区分合理表达意见与情绪性、动机性反抗，以避免将正常自主性误判为问题行为。', true, 14001),
  ('ADHD _Oppose', '08', '易怒情绪与情绪性反应', NULL, '易怒情绪与情绪性反应是指个体在日常互动中情绪阈值较低、容易因小事产生愤怒、不耐烦或情绪爆发的倾向，常伴随对立或违抗行为出现。该维度强调情绪层面的不稳定性，是对立行为的重要情绪基础。', true, 14002),
  ('ADHD_EmoReg', '09', '情绪调节与恢复困难', NULL, '情绪调节与恢复困难是指个体在经历情绪波动后，难以有效识别、管理或缓解自身情绪状态的倾向，表现为情绪持续时间长、难以冷静、情绪反应过后仍长时间受影响。该维度强调情绪过程管理能力，而非具体情绪内容（如愤怒或悲伤）。情绪调节与恢复困难被界定为个体在情绪被触发后，难以有效管理情绪强度、持续时间及其对行为和认知的影响。该维度强调“情绪之后发生了什么”，是理解功能受损与心理健康风险的重要桥梁。测量时关注情绪恢复、调节策略可及性以及主观失控体验。 ', true, 15001),
  ('ADHD_Motiv', '10', '即时奖励偏好与延迟厌恶', NULL, '即时奖励偏好与延迟厌恶是指个体在决策和行为选择中，更倾向于即时、低成本回报，而对需要等待或长期投入的目标表现出显著回避。该维度并非单纯的冲动，而是一种稳定的动机取向差异。即时奖励偏好与延迟厌恶被界定为个体在面对需要等待、持续投入或延迟回报的任务时，主观动机显著下降的稳定倾向。该维度强调“等待本身的心理成本”，而非能力不足或懒惰。其测量对于理解学习坚持、目标管理与数字依赖具有重要价值。 ', true, 16001),
  ('16PF', '01', '乐群性', 'A1	INTEGER	"I know how to comfort others" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
A2	INTEGER	"I enjoy bringing people together" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
A3	INTEGER	"I feel others'' emotions" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
A4	INTEGER	"I take an interest in other people''s lives" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
A5	INTEGER	"I cheer people up" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
A6	INTEGER	"I make people feel at ease" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
A7	INTEGER	"I take time out for others" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
A8	INTEGER	"I don''t like to get involved in other people''s problems" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
A9	INTEGER	"I am not really interested in others" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
A10	INTEGER	"I try not to think about the needy" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B1	INTEGER	"I make insightful remarks" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B2	INTEGER	"I know the answers to many questions" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B3	INTEGER	"I tend to analyze things" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B4	INTEGER	"I use my brain" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B5	INTEGER	"I learn quickly" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B6	INTEGER	"I counter others'' arguments" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B7	INTEGER	"I reflect on things before acting" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B8	INTEGER	"I weigh the pros against the cons" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B9	INTEGER	"I consider myself an average person" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B10	INTEGER	"I get confused easily" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B11	INTEGER	"I know that I am not a special person" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B12	INTEGER	"I have a poor vocabulary" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
B13	INTEGER	"I skip difficult words while reading" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
C1	INTEGER	"I seldom feel blue" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
C2	INTEGER	"I feel comfortable with myself" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
C3	INTEGER	"I readily overcome setbacks" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
C4	INTEGER	"I am relaxed most of the time" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
C5	INTEGER	"I am not easily frustrated" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
C6	INTEGER	"I have frequent mood swings" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
C7	INTEGER	"I often feel blue" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
C8	INTEGER	"I dislike myself" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
C9	INTEGER	"I feel desperate" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
C10	INTEGER	"I am easily discouraged" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
D1	INTEGER	"I take charge" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
D2	INTEGER	"I want to be in charge" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
D3	INTEGER	"I say what I think" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
D4	INTEGER	"I am not afraid of providing criticism" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
D5	INTEGER	"I take control of things" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
D6	INTEGER	"I can take strong measures" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
D7	INTEGER	"I wait for others to lead the way" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
D8	INTEGER	"I never challenge things" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
D9	INTEGER	"I let others make the decisions" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
D10	INTEGER	"I let myself be pushed around" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
E1	INTEGER	"I am the life of the party" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
E2	INTEGER	"I love large parties" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
E3	INTEGER	"I joke around a lot" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
E4	INTEGER	"I enjoy being part of a loud crowd" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
E5	INTEGER	"I amuse my friends" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
E6	INTEGER	"I act wild and crazy" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
E7	INTEGER	"I seldom joke around" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
E8	INTEGER	"I don''t like crowded events" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
E9	INTEGER	"I am the last to laugh at a joke" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
E10	INTEGER	"I dislike loud music" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
F1	INTEGER	"I believe laws should be strictly enforced" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
F2	INTEGER	"I try to follow the rules" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
F3	INTEGER	"I believe in one true religion" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
F4	INTEGER	"I respect authority" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
F5	INTEGER	"I like to stand during the national anthem" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
F6	INTEGER	"I resist authority" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
F7	INTEGER	"I break rules" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
F8	INTEGER	"I use swear words" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
F9	INTEGER	"I oppose authority" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
F10	INTEGER	"I know how to get around the rules" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
G1	INTEGER	"I feel comfortable around people" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
G2	INTEGER	"I talk to a lot of different people at parties" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
G3	INTEGER	"I don''t mind being the center of attention" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
G4	INTEGER	"I make friends easily" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
G5	INTEGER	"I start conversations" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
G6	INTEGER	"I find it difficult to approach others" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
G7	INTEGER	"I often feel uncomfortable around others" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
G8	INTEGER	"I have little to say" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
G9	INTEGER	"I am quiet around strangers" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
G10	INTEGER	"I keep in the background" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
H1	INTEGER	"I like to read" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
H2	INTEGER	"I enjoy discussing movies and books with others" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
H3	INTEGER	"I read a lot" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
H4	INTEGER	"I don''t like action movies" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
H5	INTEGER	"I cry during movies" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
H6	INTEGER	"I love flowers" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
H7	INTEGER	"I do not enjoy watching dance performances" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
H8	INTEGER	"I do not like poetry" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
H9	INTEGER	"I dislike works of fiction" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
H10	INTEGER	"I rarely notice my emotional reactions" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
I1	INTEGER	"I find it hard to forgive others" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
I2	INTEGER	"I suspect hidden motives in others" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
I3	INTEGER	"I am wary of others" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
I4	INTEGER	"I distrust people" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
I5	INTEGER	"I believe that people seldom tell you the whole truth" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
I6	INTEGER	"I believe that people are essentially evil" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
I7	INTEGER	"I trust what people say" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
I8	INTEGER	"I trust others" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
I9	INTEGER	"I believe that others have good intentions" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
I10	INTEGER	"I believe that people are basically moral" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
J1	INTEGER	"I do things that others find strange" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
J2	INTEGER	"I like to get lost in thought" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
J3	INTEGER	"I enjoy wild flights of fantasy" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
J4	INTEGER	"I love to daydream" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
J5	INTEGER	"I swim against the current" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
J6	INTEGER	"I take deviant positions" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
J7	INTEGER	"I do unexpected things" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
J8	INTEGER	"I do things by the book" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
J9	INTEGER	"I seldom daydream" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
J10	INTEGER	"I seldom get lost in thought" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
K1	INTEGER	"I reveal little about myself" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
K2	INTEGER	"I am hard to get to know" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
K3	INTEGER	"I don''t talk a lot" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
K4	INTEGER	"I bottle up my feelings" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
K5	INTEGER	"I keep my thoughts to myself" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
K6	INTEGER	"I am open about myself to others" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
K7	INTEGER	"I am open about my feelings" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
K8	INTEGER	"I disclose my intimate thoughts" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
K9	INTEGER	"I show my feelings" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
K10	INTEGER	"I am willing to talk about myself" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
L1	INTEGER	"I am afraid that I will do the wrong thing" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
L2	INTEGER	"I feel threatened easily" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
L3	INTEGER	"I am easily hurt" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
L4	INTEGER	"I worry about things" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
L5	INTEGER	"I spend time thinking about past mistakes" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
L6	INTEGER	"I feel guilty when I say ''no''" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
L7	INTEGER	"I feel crushed by setbacks" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
L8	INTEGER	"I don''t worry about things that have already happened" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
L9	INTEGER	"I am not easily bothered by things" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was labeled as "strongly agree".
L10	INTEGER	"I don''t let others discourage me" rated on a five point scale (1-5;0 if missed). 1 was labeled as "strongly disagree", 2 was labeled as "disagree", 3 was labeled as "neither agree not disagree", 4 was labeled as "agree" and 5 was label', NULL, true, 17001),
  ('16PF', '02', '聪慧性', NULL, NULL, true, 17002),
  ('16PF', '03', '稳定性', NULL, NULL, true, 17003),
  ('16PF', '04', '恃强性', NULL, NULL, true, 17004),
  ('16PF', '05', '兴奋性', NULL, NULL, true, 17005),
  ('16PF', '06', '有恒性', NULL, NULL, true, 17006),
  ('16PF', '07', '敢为性', NULL, NULL, true, 17007),
  ('16PF', '08', '敏感性', NULL, NULL, true, 17008),
  ('16PF', '09', '怀疑性', NULL, NULL, true, 17009),
  ('16PF', '10', '幻想性', NULL, NULL, true, 17010),
  ('16PF', '11', '世故性', NULL, NULL, true, 17011),
  ('16PF', '12', '忧虑性', NULL, NULL, true, 17012),
  ('16PF', '13', '实验性', NULL, NULL, true, 17013),
  ('16PF', '14', '独立性', NULL, NULL, true, 17014),
  ('16PF', '15', '自律性', NULL, NULL, true, 17015),
  ('16PF', '16', '紧张性', NULL, NULL, true, 17016),
  ('Achenbach_YSR', '01', '焦虑/抑郁', NULL, NULL, true, 18001),
  ('Achenbach_YSR', '02', '退缩/抑郁', NULL, NULL, true, 18002),
  ('Achenbach_YSR', '03', '躯体主诉', NULL, NULL, true, 18003),
  ('Achenbach_YSR', '04', '社会交往问题', NULL, NULL, true, 18004),
  ('Achenbach_YSR', '05', '思维问题', NULL, NULL, true, 18005),
  ('Achenbach_YSR', '06', '注意力问题', NULL, NULL, true, 18006),
  ('Achenbach_YSR', '07', '违纪行为', NULL, NULL, true, 18007),
  ('Achenbach_YSR', '08', '攻击性行为', NULL, NULL, true, 18008),
  ('Achenbach_CBCL', '01', '焦虑/抑郁', NULL, NULL, true, 19001),
  ('Achenbach_CBCL', '02', '退缩/抑郁', NULL, NULL, true, 19002),
  ('Achenbach_CBCL', '03', '躯体主诉', NULL, NULL, true, 19003),
  ('Achenbach_CBCL', '04', '社会交往问题', NULL, NULL, true, 19004),
  ('Achenbach_CBCL', '05', '思维问题', NULL, NULL, true, 19005),
  ('Achenbach_CBCL', '06', '注意力问题', NULL, NULL, true, 19006),
  ('Achenbach_CBCL', '07', '违纪行为', NULL, NULL, true, 19007),
  ('Achenbach_CBCL', '08', '攻击性行为', NULL, NULL, true, 19008)
ON CONFLICT (group_code, code) DO UPDATE SET
  name = EXCLUDED.name,
  desc_casual = EXCLUDED.desc_casual,
  desc_academic = EXCLUDED.desc_academic,
  active = EXCLUDED.active,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();

COMMIT;
