import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import data from '../../dataset/assessment_data.json' with { type: 'json' };

const currentDir = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(currentDir, 'assessment_directory_seed.sql');

function sql(value) {
  if (value === null || value === undefined || value === '') return 'NULL';
  return `'${String(value).replaceAll("'", "''")}'`;
}

const lines = [
  '-- Generated by backend/ingestion/generate_assessment_directory_seed.mjs',
  '-- Idempotent seed data for the public assessment directory tables.',
  '',
  'BEGIN;',
  '',
];

const modules = new Map();

data.all_groups.forEach((group, groupIndex) => {
  if (!modules.has(group.module_cn)) {
    modules.set(group.module_cn, {
      module_cn: group.module_cn,
      module_code: group.module_code,
      sort_order: modules.size + 1,
    });
  }
});

lines.push('INSERT INTO assessment_modules (module_cn, module_code, active, sort_order)');
lines.push('VALUES');
lines.push(
  Array.from(modules.values())
    .map(
      (module) =>
        `  (${sql(module.module_cn)}, ${module.module_code}, true, ${module.sort_order})`
    )
    .join(',\n') + '\nON CONFLICT (module_cn) DO UPDATE SET\n' +
      '  module_code = EXCLUDED.module_code,\n' +
      '  active = EXCLUDED.active,\n' +
      '  sort_order = EXCLUDED.sort_order,\n' +
      '  updated_at = now();'
);
lines.push('');

lines.push(
  'INSERT INTO assessment_groups (code, title_en, title_cn, title_full, module_cn, module_code, active, sort_order)'
);
lines.push('VALUES');
lines.push(
  data.all_groups
    .map(
      (group, index) =>
        `  (${sql(group.code)}, ${sql(group.title_en)}, ${sql(group.title_cn)}, ${sql(
          group.title_full
        )}, ${sql(group.module_cn)}, ${group.module_code}, true, ${index + 1})`
    )
    .join(',\n') + '\nON CONFLICT (code) DO UPDATE SET\n' +
      '  title_en = EXCLUDED.title_en,\n' +
      '  title_cn = EXCLUDED.title_cn,\n' +
      '  title_full = EXCLUDED.title_full,\n' +
      '  module_cn = EXCLUDED.module_cn,\n' +
      '  module_code = EXCLUDED.module_code,\n' +
      '  active = EXCLUDED.active,\n' +
      '  sort_order = EXCLUDED.sort_order,\n' +
      '  updated_at = now();'
);
lines.push('');

const measures = data.all_groups.flatMap((group, groupIndex) =>
  group.measures.map((measure, measureIndex) => ({
    ...measure,
    group_code: group.code,
    sort_order: groupIndex * 1000 + measureIndex + 1,
  }))
);

lines.push(
  'INSERT INTO assessment_measures (group_code, code, name, desc_casual, desc_academic, active, sort_order)'
);
lines.push('VALUES');
lines.push(
  measures
    .map(
      (measure) =>
        `  (${sql(measure.group_code)}, ${sql(measure.code)}, ${sql(measure.name)}, ${sql(
          measure.desc_casual
        )}, ${sql(measure.desc_academic)}, true, ${measure.sort_order})`
    )
    .join(',\n') + '\nON CONFLICT (group_code, code) DO UPDATE SET\n' +
      '  name = EXCLUDED.name,\n' +
      '  desc_casual = EXCLUDED.desc_casual,\n' +
      '  desc_academic = EXCLUDED.desc_academic,\n' +
      '  active = EXCLUDED.active,\n' +
      '  sort_order = EXCLUDED.sort_order,\n' +
      '  updated_at = now();'
);
lines.push('');
lines.push('COMMIT;');
lines.push('');

writeFileSync(outputPath, lines.join('\n'), 'utf8');

console.log(
  JSON.stringify({
    outputPath,
    moduleCount: modules.size,
    groupCount: data.all_groups.length,
    measureCount: measures.length,
  })
);
